spring.application.name=parking-building-management-system

# ==================== SQL Server Configuration ====================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==================== JPA / Hibernate Configuration ====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==================== Server Configuration ====================
server.port=${APP_PORT}

# ==================== VNPAY Sandbox Configuration ====================
vnpay.tmn-code=2XKCYOIK
vnpay.hash-secret=GZ4CG224HI4KOZUR2I8PWREJQQAVTWCX
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://bash-primate-glucose.ngrok-free.dev/api/v1/payments/vnpay-ipn

# ==================== JWT Configuration ====================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ==================== JSON/Jackson Configuration ====================
spring.jackson.property-naming-strategy=SNAKE_CASE
